function [events,byRunBand,distribution] = AuditSeverity(csvPath,outputStem)
%AUDITSEVERITY Audit mechanism variation without tuning on holdout data.
%   Only applied add events are matched by (run,eventIndex). Bands use fixed
%   predeclared thresholds: low<0.20, medium<0.50, high>=0.50.
if nargin < 2 || isempty(outputStem), outputStem = 'severity_audit'; end
T = readtable(csvPath);
full = T(strcmp(T.algorithm,'EAT-PSO') & ...
    strcmp(T.eventType,'add') & logical(T.eventApplied),:);
assert(~isempty(full),'No applied add events for Full EAT.');
rows = repmat(struct('level','','run',0,'eventIndex',0,'eventTime',0, ...
    'band','','change',0,'urgency',0,'routeImpact',0,'severity',0, ...
    'guideWeight',0,'warmFeasible',false,'fixedFeasible',false, ...
    'fullFeasible',false,'warmLate',NaN,'fixedLate',NaN, ...
    'fullLate',NaN,'warmFirstFE',inf,'fixedFirstFE',inf, ...
    'fullFirstFE',inf),0,1);
for i = 1:height(full)
    f = full(i,:);
    key = T.run==f.run & T.eventIndex==f.eventIndex & ...
        strcmp(T.level,f.level) & strcmp(T.eventType,'add');
    w = T(key & strcmp(T.algorithm,'Warm-PSO'),:);
    x = T(key & strcmp(T.algorithm,'EAT-FixedSeverity'),:);
    assert(height(w)==1 && height(x)==1);
    assert(w.eventApplied && x.eventApplied, ...
        'Add event was not applied in all policies.');
    if f.eventSeverity<0.20, band = 'low';
    elseif f.eventSeverity<0.50, band = 'medium';
    else, band = 'high'; end
    row = struct('level',f.level{1},'run',f.run, ...
        'eventIndex',f.eventIndex,'eventTime',f.eventTime, ...
        'band',band,'change',f.severityOrderChange, ...
        'urgency',f.severityUrgency, ...
        'routeImpact',f.severityRouteImpact, ...
        'severity',f.eventSeverity,'guideWeight',f.guideWeight, ...
        'warmFeasible',logical(w.isFeasible), ...
        'fixedFeasible',logical(x.isFeasible), ...
        'fullFeasible',logical(f.isFeasible), ...
        'warmLate',w.totalLate,'fixedLate',x.totalLate, ...
        'fullLate',f.totalLate,'warmFirstFE',w.firstFeasibleFE, ...
        'fixedFirstFE',x.firstFeasibleFE, ...
        'fullFirstFE',f.firstFeasibleFE);
    rows(end+1) = row; %#ok<AGROW>
end
events = struct2table(rows);
bands = {'low','medium','high'};
R = repmat(struct('level','','run',0,'band','','nAddEvents',0, ...
    'warmFeasibleRate',NaN,'fixedFeasibleRate',NaN, ...
    'fullFeasibleRate',NaN,'warmLate',NaN,'fixedLate',NaN, ...
    'fullLate',NaN,'warmCappedFE',NaN,'fixedCappedFE',NaN, ...
    'fullCappedFE',NaN),0,1);
maxFE = max(T.functionEvaluations);
for r = unique(events.run)'
    for b = 1:numel(bands)
        S = events(events.run==r & strcmp(events.band,bands{b}),:);
        if isempty(S), continue; end
        item = struct('level',S.level{1},'run',r,'band',bands{b}, ...
            'nAddEvents',height(S), ...
            'warmFeasibleRate',mean(S.warmFeasible), ...
            'fixedFeasibleRate',mean(S.fixedFeasible), ...
            'fullFeasibleRate',mean(S.fullFeasible), ...
            'warmLate',mean(S.warmLate),'fixedLate',mean(S.fixedLate), ...
            'fullLate',mean(S.fullLate), ...
            'warmCappedFE',mean(min(S.warmFirstFE,maxFE+1)), ...
            'fixedCappedFE',mean(min(S.fixedFirstFE,maxFE+1)), ...
            'fullCappedFE',mean(min(S.fullFirstFE,maxFE+1)));
        R(end+1) = item; %#ok<AGROW>
    end
end
byRunBand = struct2table(R);
distribution = table(min(events.severity),median(events.severity), ...
    max(events.severity),std(events.severity), ...
    min(events.change),max(events.change), ...
    min(events.urgency),max(events.urgency), ...
    min(events.routeImpact),max(events.routeImpact), ...
    sum(strcmp(events.band,'low')),sum(strcmp(events.band,'medium')), ...
    sum(strcmp(events.band,'high')), ...
    'VariableNames',{'severityMin','severityMedian','severityMax', ...
    'severityStd','changeMin','changeMax','urgencyMin','urgencyMax', ...
    'routeMin','routeMax','lowCount','mediumCount','highCount'});
outDir = fullfile(fileparts(mfilename('fullpath')),'results');
writetable(events,fullfile(outDir,[outputStem,'_events.csv']));
writetable(byRunBand,fullfile(outDir,[outputStem,'_run_bands.csv']));
writetable(distribution,fullfile(outDir,[outputStem,'_distribution.csv']));
disp(distribution);
end
