function [perRun,summary] = SummarizeAddRecovery(csvPath,outputStem)
%SUMMARIZEADDRECOVERY Prespecified add-event run-level endpoints.
%   Add events are exogenous and must apply in every policy. Censored
%   first-feasible FE uses maxFE+1 for non-recovery, reported alongside
%   recovery fraction. Scenario runs, not event rows, are replicates.
if nargin < 2 || isempty(outputStem), outputStem = 'add_recovery'; end
T = readtable(csvPath);
add = T(strcmp(T.eventType,'add'),:);
assert(~isempty(add) && all(logical(add.eventApplied)), ...
    'Every add event must apply for the paired primary analysis.');
levels = unique(add.level,'stable');
algorithms = unique(add.algorithm,'stable');
R = repmat(struct('level','','run',0,'algorithm','', ...
    'nAdd',0,'addFeasibleRate',NaN,'addMeanLate',NaN, ...
    'addMeanCappedFirstFE',NaN,'addMeanResponse',NaN, ...
    'addMeanDistance',NaN,'addMeanFE',NaN, ...
    'cancelAppliedRate',NaN),0,1);
for l = 1:numel(levels)
    for r = unique(add.run(:))'
        for a = 1:numel(algorithms)
            idx = strcmp(add.level,levels{l}) & add.run==r & ...
                strcmp(add.algorithm,algorithms{a});
            S = add(idx,:);
            if isempty(S), continue; end
            C = T(strcmp(T.level,levels{l}) & T.run==r & ...
                strcmp(T.algorithm,algorithms{a}) & ...
                strcmp(T.eventType,'cancel'),:);
            cancelRate = NaN;
            if ~isempty(C), cancelRate = mean(double(C.eventApplied)); end
            capped = min(S.firstFeasibleFE,S.functionEvaluations+1);
            item = struct('level',levels{l},'run',r, ...
                'algorithm',algorithms{a},'nAdd',height(S), ...
                'addFeasibleRate',mean(double(S.isFeasible)), ...
                'addMeanLate',mean(S.totalLate), ...
                'addMeanCappedFirstFE',mean(capped), ...
                'addMeanResponse',mean(S.responseTime), ...
                'addMeanDistance',mean(S.distance), ...
                'addMeanFE',mean(S.functionEvaluations), ...
                'cancelAppliedRate',cancelRate);
            R(end+1) = item; %#ok<AGROW>
        end
    end
end
perRun = struct2table(R);
S = repmat(struct('level','','algorithm','','nRuns',0, ...
    'addFeasibleMean',NaN,'addFeasibleStd',NaN, ...
    'cappedFirstFEMean',NaN,'cappedFirstFEStd',NaN, ...
    'addLateMean',NaN,'addLateStd',NaN, ...
    'responseMean',NaN,'responseStd',NaN, ...
    'cancelAppliedMean',NaN),0,1);
for l = 1:numel(levels)
    for a = 1:numel(algorithms)
        Q = perRun(strcmp(perRun.level,levels{l}) & ...
            strcmp(perRun.algorithm,algorithms{a}),:);
        if isempty(Q), continue; end
        item = struct('level',levels{l},'algorithm',algorithms{a}, ...
            'nRuns',height(Q),'addFeasibleMean',mean(Q.addFeasibleRate), ...
            'addFeasibleStd',std(Q.addFeasibleRate), ...
            'cappedFirstFEMean',mean(Q.addMeanCappedFirstFE), ...
            'cappedFirstFEStd',std(Q.addMeanCappedFirstFE), ...
            'addLateMean',mean(Q.addMeanLate), ...
            'addLateStd',std(Q.addMeanLate), ...
            'responseMean',mean(Q.addMeanResponse), ...
            'responseStd',std(Q.addMeanResponse), ...
            'cancelAppliedMean',mean(Q.cancelAppliedRate,'omitnan'));
        S(end+1) = item; %#ok<AGROW>
    end
end
summary = struct2table(S);
outDir = fullfile(fileparts(mfilename('fullpath')),'results');
writetable(perRun,fullfile(outDir,[outputStem,'_runs.csv']));
writetable(summary,fullfile(outDir,[outputStem,'_summary.csv']));
disp(summary);
end
